[package]
name = "vulkan-rust"
version = "0.1.0"
authors = ["Dominik Baumann <hey@sobrinth.com>"]
edition = "2024"

[dependencies]
ash = "0.38"
ash-window = "0.13"
winit = "0.30"
log = "0.4"
env_logger = "0.11"
itertools = "0.14.0"
