[package]
name = "render-thing"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
engine.workspace = true
winit.workspace = true
env_logger.workspace = true